In [1]:
import pandas as pd
import numpy as np
import nltk
from nltk.stem import WordNetLemmatizer
from nltk.corpus import wordnet 
from nltk.corpus import stopwords
from num2words import num2words # needed to install num2words first
import string

In [46]:
nltk.download('averaged_perceptron_tagger')

[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     C:\Users\HJMit\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping taggers\averaged_perceptron_tagger.zip.

True

In [2]:
df=pd.read_json('./News_Category_Dataset_v3.json', lines=True)

In [3]:
## Remove duplicate articles by link
df=df[df['link'].duplicated()==False]

In [5]:
temp = df.head(100)

In [6]:
temp.groupby("category").count().sort_values(by=["link"])

                link  headline  short_description  authors  date
category
COMEDY             1         1                  1        1     1
EDUCATION          1         1                  1        1     1
PARENTING          1         1                  1        1     1
TECH               2         2                  2        2     2
WEIRD NEWS         2         2                  2        2     2
CULTURE & ARTS     5         5                  5        5     5
ENVIRONMENT        5         5                  5        5     5
SPORTS             7         7                  7        7     7
POLITICS          16        16                 16       16    16
ENTERTAINMENT     17        17                 17       17    17
WORLD NEWS        20        20                 20       20    20
U.S. NEWS         23        23                 23       23    23

In [8]:
## create new df with only categories we want
df = temp.loc[temp['category'].isin(["U.S. NEWS", "WORLD NEWS", "ENTERTAINMENT", "POLITICS", "SPORTS"])]

In [9]:
## NB!! reset the indices! 
## Need this in order to accurately match the rows in this df with their if-tdf vectors
df = df.reset_index(drop=True)

In [10]:
df

,link,headline,category,short_description,authors,date
0,https://www.huffpost.com/entry/covid-boosters-...,Over 4 Million Americans Roll Up Sleeves For O...,U.S. NEWS,Health experts said it is too early to predict...,"Carla K. Johnson, AP",2022-09-23
1,https://www.huffpost.com/entry/american-airlin...,"American Airlines Flyer Charged, Banned For Li...",U.S. NEWS,He was subdued by passengers and crew when he ...,Mary Papenfuss,2022-09-23
2,https://www.huffpost.com/entry/amy-cooper-lose...,Woman Who Called Cops On Black Bird-Watcher Lo...,U.S. NEWS,Amy Cooper accused investment firm Franklin Te...,Nina Golgowski,2022-09-22
3,https://www.huffpost.com/entry/belk-worker-fou...,Cleaner Was Dead In Belk Bathroom For 4 Days B...,U.S. NEWS,The 63-year-old woman was seen working at the ...,,2022-09-22
4,https://www.huffpost.com/entry/reporter-gets-a...,Reporter Gets Adorable Surprise From Her Boyfr...,U.S. NEWS,"""Who's that behind you?"" an anchor for New Yor...",Elyse Wanshel,2022-09-22
...,...,...,...,...,...,...
78,https://www.huffpost.com/entry/fairview-fire-c...,Fast-Moving Fairview Fire Kills At Least 2 In ...,U.S. NEWS,A second fire killed two people in Northern Ca...,Nick Visser,2022-09-06
79,https://www.huffpost.com/entry/kody-clemens-st...,"Kody Clemens Strikes Out MVP Shohei Ohtani, Tr...",SPORTS,The Detroit Tigers' rookie utility player got ...,,2022-09-06
80,https://www.huffpost.com/entry/jackson-water-p...,Mississippi Governor Says Water Pressure Is No...,U.S. NEWS,"The city remains under a boil water notice, wh...",Marita Vlachou,2022-09-06
81,https://www.huffpost.com/entry/meta-400-millio...,"Meta, Parent Company Of Instagram, Fined $400 ...",U.S. NEWS,The social media giant was fined for violation...,Nick Visser,2022-09-06
82,https://www.huffpost.com/entry/uvalde-texas-sh...,School Starts Today For Survivors Of Deadly Ma...,U.S. NEWS,There is new high fencing around the Texas com...,"Paul J. Weber, AP",2022-09-06

## Next
clean headline and short description

create combo column for cleaned strings

In [11]:
## making columns
df=df[df['link'].duplicated()==False] ###Remove duplicate articles by link
df['headline_cleaned']=df['headline']
df['short_description_cleaned']=df['short_description']
df

,link,headline,category,short_description,authors,date,headline_cleaned,short_description_cleaned
0,https://www.huffpost.com/entry/covid-boosters-...,Over 4 Million Americans Roll Up Sleeves For O...,U.S. NEWS,Health experts said it is too early to predict...,"Carla K. Johnson, AP",2022-09-23,Over 4 Million Americans Roll Up Sleeves For O...,Health experts said it is too early to predict...
1,https://www.huffpost.com/entry/american-airlin...,"American Airlines Flyer Charged, Banned For Li...",U.S. NEWS,He was subdued by passengers and crew when he ...,Mary Papenfuss,2022-09-23,"American Airlines Flyer Charged, Banned For Li...",He was subdued by passengers and crew when he ...
2,https://www.huffpost.com/entry/amy-cooper-lose...,Woman Who Called Cops On Black Bird-Watcher Lo...,U.S. NEWS,Amy Cooper accused investment firm Franklin Te...,Nina Golgowski,2022-09-22,Woman Who Called Cops On Black Bird-Watcher Lo...,Amy Cooper accused investment firm Franklin Te...
3,https://www.huffpost.com/entry/belk-worker-fou...,Cleaner Was Dead In Belk Bathroom For 4 Days B...,U.S. NEWS,The 63-year-old woman was seen working at the ...,,2022-09-22,Cleaner Was Dead In Belk Bathroom For 4 Days B...,The 63-year-old woman was seen working at the ...
4,https://www.huffpost.com/entry/reporter-gets-a...,Reporter Gets Adorable Surprise From Her Boyfr...,U.S. NEWS,"""Who's that behind you?"" an anchor for New Yor...",Elyse Wanshel,2022-09-22,Reporter Gets Adorable Surprise From Her Boyfr...,"""Who's that behind you?"" an anchor for New Yor..."
...,...,...,...,...,...,...,...,...
78,https://www.huffpost.com/entry/fairview-fire-c...,Fast-Moving Fairview Fire Kills At Least 2 In ...,U.S. NEWS,A second fire killed two people in Northern Ca...,Nick Visser,2022-09-06,Fast-Moving Fairview Fire Kills At Least 2 In ...,A second fire killed two people in Northern Ca...
79,https://www.huffpost.com/entry/kody-clemens-st...,"Kody Clemens Strikes Out MVP Shohei Ohtani, Tr...",SPORTS,The Detroit Tigers' rookie utility player got ...,,2022-09-06,"Kody Clemens Strikes Out MVP Shohei Ohtani, Tr...",The Detroit Tigers' rookie utility player got ...
80,https://www.huffpost.com/entry/jackson-water-p...,Mississippi Governor Says Water Pressure Is No...,U.S. NEWS,"The city remains under a boil water notice, wh...",Marita Vlachou,2022-09-06,Mississippi Governor Says Water Pressure Is No...,"The city remains under a boil water notice, wh..."
81,https://www.huffpost.com/entry/meta-400-millio...,"Meta, Parent Company Of Instagram, Fined $400 ...",U.S. NEWS,The social media giant was fined for violation...,Nick Visser,2022-09-06,"Meta, Parent Company Of Instagram, Fined $400 ...",The social media giant was fined for violation...
82,https://www.huffpost.com/entry/uvalde-texas-sh...,School Starts Today For Survivors Of Deadly Ma...,U.S. NEWS,There is new high fencing around the Texas com...,"Paul J. Weber, AP",2022-09-06,School Starts Today For Survivors Of Deadly Ma...,There is new high fencing around the Texas com...

In [12]:
def get_wordnet_pos(treebank_tag):
    ##### This function converts part of speech tags to a form the lemmatizer can use
    if treebank_tag.startswith('J'):
        return 'a'
    elif treebank_tag.startswith('V'):
        return 'v'
    elif treebank_tag.startswith('N'):
        return 'n'
    elif treebank_tag.startswith('R'):
        return 'r'
    else:
        return 'n'

In [13]:
def preprocess_text(tstring):
    temp=''
    
    ## tokenize the words from the string
    tlist=nltk.word_tokenize(tstring.replace('-', ' '))
    
    ## remove punctation
    tlist =[w.lower() for w in tlist if (w not in string.punctuation) and (w not in ['\u2019', '\'s'])]
    
    ## convert numbers to words
    #tlist=[num2words(w) if w.isnumeric() else w for w in tlist]
    
    ## Tag part of speech
    tlist=nltk.pos_tag(tlist)
    
    ## convert to lowercase and remove stop words
    tlist=[w for w in tlist if not w[0] in set(stopwords.words('english'))]

    for word in tlist:
        #print(word[0], get_wordnet_pos(word[1]))
        if len(temp)!=0:
            #print(WordNetLemmatizer().lemmatize(word[0].lower(),get_wordnet_pos(word[1])))
            temp += ' ' + WordNetLemmatizer().lemmatize(word[0].lower(),get_wordnet_pos(word[1]))
        else: 
            #print(WordNetLemmatizer().lemmatize(word[0].lower(),get_wordnet_pos(word[1])))
            temp += WordNetLemmatizer().lemmatize(word[0].lower(),get_wordnet_pos(word[1]))
    return temp

In [14]:
## Clean headlines
df['short_description_cleaned']=df['short_description_cleaned'].apply(lambda x: preprocess_text(x))
df['headline_cleaned']=df['headline_cleaned'].apply(lambda x: preprocess_text(x))

In [15]:
## create new column with two cleaned cells concatenated
df['cleaned_words'] = df['headline_cleaned'] + ' ' + df['short_description_cleaned']

## TF-IDF

In [16]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [17]:
## Calcuate TF-IDF and create vectors
v = TfidfVectorizer()
x = v.fit_transform(df['cleaned_words'])

In [18]:
## Save the list of vectors as a df, along with the words each point corresponds to
df_vectors = pd.DataFrame(x.toarray(), columns=v.get_feature_names_out())

## rename columns in original df 
## (it causes problems if one of the words from text is same as another column name)
df = df.rename(columns={"link":"link_col", 
                        "headline":"headline_col", 
                        "category":"category_col",
                        "authors":"authors_col", 
                        "date":"date_col"})

## concatenate the two dfs on the vertical axis
whole_df = pd.concat([df, df_vectors], axis = 1)

In [190]:
whole_df

,link_col,headline_col,category_col,short_description,authors_col,date_col,headline_cleaned,short_description_cleaned,cleaned_words,000,...,worldwide,worsen,would,wreath,writer,year,york,young,youtube,zaporizhzhia
0,https://www.huffpost.com/entry/covid-boosters-...,Over 4 Million Americans Roll Up Sleeves For O...,U.S. NEWS,Health experts said it is too early to predict...,"Carla K. Johnson, AP",2022-09-23,4 million american roll sleeve omicron target ...,health expert say early predict whether demand...,4 million american roll sleeve omicron target ...,0.0,...,0.0,0.0,0.175138,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0
1,https://www.huffpost.com/entry/american-airlin...,"American Airlines Flyer Charged, Banned For Li...",U.S. NEWS,He was subdued by passengers and crew when he ...,Mary Papenfuss,2022-09-23,american airline flyer charge ban life punch f...,subdue passenger crew flee back aircraft confr...,american airline flyer charge ban life punch f...,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0
2,https://www.huffpost.com/entry/amy-cooper-lose...,Woman Who Called Cops On Black Bird-Watcher Lo...,U.S. NEWS,Amy Cooper accused investment firm Franklin Te...,Nina Golgowski,2022-09-22,woman call cop black bird watcher lose lawsuit...,amy cooper accuse investment firm franklin tem...,woman call cop black bird watcher lose lawsuit...,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0
3,https://www.huffpost.com/entry/belk-worker-fou...,Cleaner Was Dead In Belk Bathroom For 4 Days B...,U.S. NEWS,The 63-year-old woman was seen working at the ...,,2022-09-22,cleaner dead belk bathroom 4 day body find police,63 year old woman see work south carolina stor...,cleaner dead belk bathroom 4 day body find pol...,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.137058,0.000000,0.0,0.0,0.0
4,https://www.huffpost.com/entry/reporter-gets-a...,Reporter Gets Adorable Surprise From Her Boyfr...,U.S. NEWS,"""Who's that behind you?"" an anchor for New Yor...",Elyse Wanshel,2022-09-22,reporter get adorable surprise boyfriend live tv,`` behind '' anchor new york pix11 ask journal...,reporter get adorable surprise boyfriend live ...,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.000000,0.232446,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
78,https://www.huffpost.com/entry/fairview-fire-c...,Fast-Moving Fairview Fire Kills At Least 2 In ...,U.S. NEWS,A second fire killed two people in Northern Ca...,Nick Visser,2022-09-06,fast move fairview fire kill least 2 california,second fire kill two people northern californi...,fast move fairview fire kill least 2 californi...,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0
79,https://www.huffpost.com/entry/kody-clemens-st...,"Kody Clemens Strikes Out MVP Shohei Ohtani, Tr...",SPORTS,The Detroit Tigers' rookie utility player got ...,,2022-09-06,kody clemens strike mvp shohei ohtani trail da...,detroit tiger rookie utility player get press ...,kody clemens strike mvp shohei ohtani trail da...,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0
80,https://www.huffpost.com/entry/jackson-water-p...,Mississippi Governor Says Water Pressure Is No...,U.S. NEWS,"The city remains under a boil water notice, wh...",Marita Vlachou,2022-09-06,mississippi governor say water pressure 'solid...,city remain boil water notice first go effect ...,mississippi governor say water pressure 'solid...,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0
81,https://www.huffpost.com/entry/meta-400-millio...,"Meta, Parent Company Of Instagram, Fined $400 ...",U.S. NEWS,The social media giant was fined for violation...,Nick Visser,2022-09-06,meta parent company instagram fin 400 million ...,social medium giant fin violation data privacy...,meta parent company instagram fin 400 million ...,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0
82,https://www.huffpost.com/entry/uvalde-texas-sh...,School Starts Today For Survivors Of Deadly Ma...,U.S. NEWS,There is new high fencing around the Texas com...,"Paul J. Weber, AP",2022-09-06,school start today survivor deadly mass shooti...,new high fencing around texas community public...,school start today survivor deadly mass shooti...,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0

## train_test_split

In [20]:
from sklearn.model_selection import train_test_split

In [21]:
## Make the split
news_train, news_test = train_test_split(whole_df,
                                            random_state = 546,
                                            shuffle = True,
                                            stratify = whole_df['category_col'])